### ISSUE TITLE
iterated_prisoner output table does not fit

### ISSUE THREAD

**Issue by colingeniet** [colingeniet/prisoners-dilemma#3]
The latex table created by `iterated_prisoner` is too large and does not fit the page. 
Break it in two parts ?

**Comment by Karnaj** [comment]
Yeah, I was thinking about a parameter, the number of row of each table. Thus, with 20 strategy, it would permit to create 4 table (if the parameter is 5).

**Comment by colingeniet** [comment]
I set the maximum number of columns to 6 (plus the names column). That way, there are only 2 tables with the 11 default strategies.
